"""MixinStatus added Post et Poslike

Revision ID: 03841f262b3c
Revises: 8d0a78d7373e
Create Date: 2026-01-30 13:27:13.954120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '03841f262b3c'
down_revision: Union[str, Sequence[str], None] = '8d0a78d7373e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ajout de l'ENUM:
    status_enum = postgresql.ENUM("ACTIVE", "DELETED", "ARCHIVED", "SIGNALED", name="status_enum")
    status_enum.create(op.get_bind(), checkfirst=True)

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postlikes', sa.Column('status', sa.Enum('ACTIVE', 'DELETED', 'ARCHIVED', 'SIGNALED', name='status_enum'), nullable=False, server_default='ACTIVE'))
    op.add_column('users', sa.Column('status', sa.Enum('ACTIVE', 'DELETED', 'ARCHIVED', 'SIGNALED', name='status_enum'), nullable=False, server_default='ACTIVE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('postlikes', 'status')
    # ### end Alembic commands ###
    
     # Supprime le type Enum
    status_enum = postgresql.ENUM('ACTIVE', 'DELETED', 'ARCHIVED', 'SIGNALED', name='status_enum')
    status_enum.drop(op.get_bind(), checkfirst=True)
