"""add status for posts

Revision ID: 68c52f73adef
Revises: 03841f262b3c
Create Date: 2026-01-30 14:34:45.609349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c52f73adef'
down_revision: Union[str, Sequence[str], None] = '03841f262b3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('status', sa.Enum('ACTIVE', 'DELETED', 'ARCHIVED', 'SIGNALED', name='status_enum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'status')
    # ### end Alembic commands ###
