"""postlike became object with pk

Revision ID: 8d0a78d7373e
Revises: ea44de49d71c
Create Date: 2026-01-30 12:49:42.864394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d0a78d7373e'
down_revision: Union[str, Sequence[str], None] = 'ea44de49d71c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postlikes', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('postlikes', sa.Column('like_type', sa.String(), server_default=sa.text("'Normal'"), nullable=False))
    op.create_unique_constraint('uq_postlike_user_post', 'postlikes', ['user_id', 'post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_postlike_user_post', 'postlikes', type_='unique')
    op.drop_column('postlikes', 'like_type')
    op.drop_column('postlikes', 'id')
    # ### end Alembic commands ###
