"""added soft delete mixin

Revision ID: c1525e413f34
Revises: 50eaed4eb23f
Create Date: 2026-01-30 22:16:50.586667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1525e413f34'
down_revision: Union[str, Sequence[str], None] = '50eaed4eb23f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postlikes', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('posts', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('posts', 'deleted_at')
    op.drop_column('postlikes', 'deleted_at')
    # ### end Alembic commands ###
